on:
  schedule:
    # Runs every hour
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest MAL history
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: MyAnimeList List Readme
        uses: MoonLGH/MAL_Autolist@testing
        with:
          username: "MoonLMAL"
          limit: "15"
          readme_path: "MoonLGH/MoonLGH"
      - name: cleaning post process
        run: rm -r -force ./MAL_Autolist
        shell: bash
      - name: MyAnimeList List Anime
        uses: MoonLGH/MAL_Autolist@testing
        with:
          username: "MoonLMAL"
          limit: "0"
          filename: "Anime.md"
          readme_path: "MoonLGH/MoonLGH"
      - name: cleaning post process
        run: rm -r -force ./MAL_Autolist
        shell: bash
      - name: MyAnimeList List Manga
        uses: MoonLGH/MAL_Autolist@testing
        with:
          username: "MoonLMAL"
          limit: "0"
          filename: "Manga.md"
          readme_path: "MoonLGH/MoonLGH"
